# Generated by Django 5.1.3 on 2025-02-16 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Profile_pic',
            new_name='profile_pic',
        ),
    ]
